services:
    mongo:
        image: mongo:6
        container_name: mongo_db
        restart: always
        environment:
            MONGO_INITDB_DATABASE: ${MONGO_DB}
            MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        ports:
            - "${MONGO_PORT}:27017"
        volumes:
            - mongo_data:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongo_express
        restart: always
        ports:
            - "${MONGO_EXPRESS_PORT}:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_SERVER: mongo
            OCR_PORT: ${OCR_PORT}
            LLM_PORT: ${LLM_PORT}

    backend:
        build: ./backend
        container_name: backend_app
        ports:
            - "${BACKEND_PORT}:5000"
        env_file:
            - .env
        environment:
            MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin
            PORT: ${BACKEND_PORT}
            JWT_SECRET: ${JWT_SECRET}
        restart: always
        volumes:
            - ./backend:/app
        depends_on:
            - mongo

    ocr_service:
        build: ./microservices/ocrService
        container_name: ocr_service
        ports:
            - "${OCR_PORT}:5010"
        volumes:
            - ./microservices/ocrService:/app
        restart: always

    llm_service:
        build: ./microservices/llmService
        container_name: llm_service
        ports:
            - "${LLM_PORT}:5020"
        volumes:
            - ./microservices/llmService:/app
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        restart: always

volumes:
    mongo_data:
    backend_node_modules:
