services:
    mongo:
        image: mongo:6
        container_name: mongo_db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        ports:
            - '27017:27017'
        volumes:
            - mongo_data:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 27016:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
            ME_CONFIG_BASICAUTH: false

    backend:
        build: ./backend
        container_name: backend_app
        depends_on:
            - mongo
        ports:
            - '5000:5000'
        environment:
            - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
            - PORT=5000
        restart: always
        volumes:
            - ./backend:/app
            - backend_node_modules:/app/node_modules
        command: ['npx', 'nodemon', 'index.ts']

    ocr_service:
        build: ./microservices/ocrService
        container_name: ocr_service
        ports:
            - '5010:5010'
        volumes:
            - ./microservices/ocrService:/app
        restart: always

    llm_service:
        build: ./microservices/llmService
        container_name: llm_service
        ports:
            - '5020:5020'
        volumes:
            - ./microservices/llmService:/app
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        restart: always

volumes:
    mongo_data:
    backend_node_modules:
