services:
    # backend:
    #   build:
    #     context: ./backend
    #     dockerfile: Dockerfile
    #   ports:
    #     - "3000:3000"
    #   depends_on:
    #     - mongo
    #   environment:
    #     - MONGO_URI=mongodb://mongo:27017/miBaseDeDatos
    #   volumes:
    #     - ./backend:/app
    #     - /app/node_modules

    mongo:
        image: mongo:6
        restart: always
        container_name: mongo_db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

        ports:
            - '27017:27017'
        volumes:
            - mongo_data:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 27016:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
            ME_CONFIG_BASICAUTH: false

volumes:
    mongo_data:
