services:
    llm_service:
        build: .
        ports:
            - '5020:5020'
        volumes:
            - .:/app
        environment:
            OPENAI_API_KEY: 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
        restart: always
